# Simple Evergreen integration that runs pytests tests.
functions:
  fetch_source:
  - command: git.get_project
    params:
      directory: sonar

  python_venv: &python_venv
    command: subprocess.exec
    type: setup
    params:
      command: virtualenv --python /opt/python/3.7/bin/python3 ./venv

  python_requirements: &python_requirements
    command: subprocess.exec
    type: setup
    params:
      working_dir: sonar
      command: ${workdir}/venv/bin/python -m pip install -r requirements-dev.txt --quiet --no-warn-script-location

  sonar_install: &sonar_install
    command: subprocess.exec
    type: setup
    params:
      working_dir: sonar
      command: ${workdir}/venv/bin/python setup.py install

  tests_unit:
  - *python_venv
  - *python_requirements
  - *sonar_install
  - command: subprocess.exec
    type: test
    params:
      working_dir: sonar
      command: ${workdir}/venv/bin/python -m pytest

  tests_lint:
  - *python_venv
  - *python_requirements
  - command: subprocess.exec
    type: test
    params:
      working_dir: sonar
      command: ${workdir}/venv/bin/python -m pylint sonar/ --fail-under=8 
    
tasks:
- name: tests_unit
  tags: ["tests"]
  commands:
  - func: fetch_source
  - func: tests_unit

- name: tests_lint
  tags: ["tests"]
  commands:
  - func: fetch_source
  - func: tests_lint

buildvariants:
- name: tests_unit
  display_name: tests_unit
  run_on:
  - ubuntu1604-test
  stepback: true
  tasks:
  - name: tests_unit
  - name: tests_lint
